const HELLO = "WS_HELLO";
const PING = "WS_PING";
const PONG = "WS_PONG";

const USER_EVENTS = {
  WS_DELETE_SENT_FRIEND_REQUEST: "WS_DELETE_SENT_FRIEND_REQUEST",
  WS_ADD_RECEIVED_FRIEND_REQUEST: "WS_ADD_RECEIVED_FRIEND_REQUEST",
  WS_DELETE_RECEIVED_FRIEND_REQUEST: "WS_DELETE_RECEIVED_FRIEND_REQUEST",
  WS_ADD_FRIEND: "WS_ADD_FRIEND",
  WS_DELETE_FRIEND: "WS_DELETE_FRIEND",
  WS_ADD_BLOCKER: "WS_ADD_BLOCKER",
  WS_DELETE_BLOCKER: "WS_DELETE_BLOCKER",
  WS_ADD_CHANNEL: "WS_ADD_CHANNEL",
  WS_SUBSCRIBE_CHANNEL: "WS_SUBSCRIBE_CHANNEL",
  WS_UNSUBSCRIBE_CHANNEL: "WS_UNSUBSCRIBE_CHANNEL"
};

const CHANNEL_EVENTS = {
  WS_FRIEND_ONLINE: "WS_FRIEND_ONLINE",
  WS_FRIEND_OFFLINE: "WS_FRIEND_OFFLINE",
  WS_UPDATE_CHANNEL: "WS_UPDATE_CHANNEL",
  WS_DELETE_CHANNEL: "WS_DELETE_CHANNEL",
  WS_DELETE_FRIEND: "WS_DELETE_FRIEND",
  WS_DELETE_FRIEND_ROOM: "WS_DELETE_FRIEND_ROOM",
  WS_ADD_MEMBER: "WS_ADD_MEMBER",
  WS_ADD_MEMBERS: "WS_ADD_MEMBERS",
  WS_DELETE_MEMBER: "WS_DELETE_MEMBER",
  WS_ADD_ADMIN: "WS_ADD_ADMIN",
  WS_DELETE_ADMIN: "WS_DELETE_ADMIN",
  WS_ADD_BAN: "WS_ADD_BAN",
  WS_DELETE_BAN: "WS_DELETE_BAN",
  WS_ADD_MESSAGE: "WS_ADD_MESSAGE",
  WS_DELETE_MESSAGE: "WS_DELETE_MESSAGE",
  WS_ADD_SEEN_MESSAGE: "WS_ADD_SEEN_MESSAGE",
  WS_ADD_POST: "WS_ADD_POST",
  WS_DELETE_POST: "WS_DELETE_POST",
  WS_ADD_POST_LIKE: "WS_ADD_POST_LIKE",
  WS_DELETE_POST_LIKE: "WS_DELETE_POST_LIKE",
  WS_ADD_COMMENT: "WS_ADD_COMMENT",
  WS_DELETE_COMMENT: "WS_DELETE_COMMENT",
  WS_ADD_COMMENT_LIKE: "WS_ADD_COMMENT_LIKE",
  WS_DELETE_COMMENT_LIKE: "WS_DELETE_COMMENT_LIKE",
  WS_ADD_WATCHER: "WS_ADD_WATCHER",
  WS_DELETE_WATCHER: "WS_DELETE_WATCHER",
  WS_ADD_VIDEO: "WS_ADD_VIDEO",
  WS_DELETE_VIDEO: "WS_DELETE_VIDEO",
  WS_REQUEST_CHANNEL_FOLLOW: "WS_REQUEST_CHANNEL_FOLLOW",
  WS_ACCEPT_CHANNEL_FOLLOW_REQUEST: "WS_ACCEPT_CHANNEL_FOLLOW_REQUEST",
  WS_REJECT_CHANNEL_FOLLOW_REQUEST: "WS_REJECT_CHANNEL_FOLLOW_REQUEST"
};

const USER_CHANNEL_EVENTS = {
  WS_JOIN_CHANNEL: "WS_JOIN_CHANNEL",
  WS_LEAVE_CHANNEL: "WS_LEAVE_CHANNEL",
  WS_UNFRIEND: "WS_UNFRIEND",
  WS_BLOCK_FRIEND: "WS_BLOCK_FRIEND"
};

const CHANNELS_EVENTS = {
  WS_UPDATE_USER: "WS_UPDATE_USER"
};

module.exports = {
  HELLO,
  PING,
  PONG,
  USER_EVENTS,
  CHANNEL_EVENTS,
  USER_CHANNEL_EVENTS,
  CHANNELS_EVENTS
};
