name: deploy on push
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        continue-on-error: true
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script_stop: false
          script: |
            cd projects/popitalk-server-ws/
            pm2 delete popitalk-server-ws
            git pull
            npm install
            env NODE_ENV=production pm2 start ./src/index.js --name "popitalk-server-ws"
            exit
